export const PROFILE_SAVE_ABOUTYOU_PI = 'PROFILE_SAVE_ABOUTYOU_PI';
export const PROFILE_SAVE_ABOUTYOU_CAREER = 'PROFILE_SAVE_ABOUTYOU_CAREER';
export const PROFILE_SAVE_ABOUTYOU_LANGUAGE = 'PROFILE_SAVE_ABOUTYOU_LANGUAGE';

export const PROFILE_SAVE_SKILLS = 'PROFILE_SAVE_SKILLS';

export const PROFILE_SAVE_JOBEXPERIENCE = 'PROFILE_SAVE_JOBEXPERIENCE';

export const PROFILE_CREATE_REQUEST = 'PROFILE_CREATE_REQUEST';
export const PROFILE_CREATE_SUCCESS = 'PROFILE_CREATE_SUCCESS';
export const PROFILE_CREATE_FAIL = 'PROFILE_CREATE_FAIL';

export const PROFILE_EMPTY = 'PROFILE_EMPTY';
