export const VACANCY_LIST_REQUEST = 'VACANCY_LIST_REQUEST';
export const VACANCY_LIST_SUCCESS = 'VACANCY_LIST_SUCCESS';
export const VACANCY_LIST_FAIL = 'VACANCY_LIST_FAIL';

export const VACANCY_DETAILS_REQUEST = 'VACANCY_DETAILS_REQUEST';
export const VACANCY_DETAILS_SUCCESS = 'VACANCY_DETAILS_SUCCESS';
export const VACANCY_DETAILS_FAIL = 'VACANCY_DETAILS_FAIL';
