export const VACANCY_LIST_REQUEST = 'VACANCY_LIST_REQUEST';
export const VACANCY_LIST_SUCCESS = 'VACANCY_LIST_SUCCESS';
export const VACANCY_LIST_FAIL = 'VACANCY_LIST_FAIL';

export const VACANCY_DETAILS_REQUEST = 'VACANCY_DETAILS_REQUEST';
export const VACANCY_DETAILS_SUCCESS = 'VACANCY_DETAILS_SUCCESS';
export const VACANCY_DETAILS_FAIL = 'VACANCY_DETAILS_FAIL';

export const VACANCY_CREATE_REQUEST = 'VACANCY_CREATE_REQUEST';
export const VACANCY_CREATE_SUCCESS = 'VACANCY_CREATE_SUCCESS';
export const VACANCY_CREATE_FAIL = 'VACANCY_CREATE_FAIL';

export const VACANCY_EMPTY = 'VACANCY_EMPTY';

export const USER_VACANCY_LIST_REQUEST = 'USER_VACANCY_LIST_REQUEST';
export const USER_VACANCY_LIST_SUCCESS = 'USER_VACANCY_LIST_SUCCESS';
export const USER_VACANCY_LIST_FAIL = 'USER_VACANCY_LIST_FAIL';
